package model.entities;


import rules.managers.RuleType;

import java.util.Map;
import java.util.Objects;


/**
 * Immutable scoring option generated by a rule for the current dice roll.
 *
 * @param type The rule that produced the option.
 * @param displayName The user-facing rule name.
 * @param description A short description shown in menus.
 * @param selectedValue The die value the option is based on when applicable.
 * @param pointsAwarded The number of points earned by taking the option.
 * @param consumedDice The dice counts removed from play when the option is applied.
 */
public record GameOption(
		RuleType type,
		String displayName,
		String description,
		Integer selectedValue,
		int pointsAwarded,
		Map<Integer, Integer> consumedDice
) {
	/**
	 * Defensively copies the consumed-dice map so the option remains immutable.
	 */
	public GameOption {
		Objects.requireNonNull(type, "type cannot be null.");
		Objects.requireNonNull(displayName, "displayName cannot be null.");
		Objects.requireNonNull(description, "description cannot be null.");
		Objects.requireNonNull(consumedDice, "consumedDice cannot be null.");
		consumedDice = Map.copyOf(consumedDice);
	}
}
